/* ══════════════════════════════════════════
   SYSTEM DE TRADUCTION FR / EN
══════════════════════════════════════════ */
const i18n = {
  fr: {
    /* NAV */
    "nav.home"        : "Accueil",
    "nav.about"       : "À propos",
    "nav.skills"      : "Compétences",
    "nav.projects"    : "Projets",
    "nav.parcours"    : "Parcours",
    "nav.cv"          : "CV",
    "nav.contact"     : "Contact",

    /* INDEX */
    "hero.label"      : "Bienvenue sur mon portfolio",
    "hero.subtitle"   : "Développeur Web & Logiciel",
    "hero.typing"     : '["Étudiant BTS SIO SLAM","Développeur en devenir","Passionné d\'informatique","En recherche d\'alternance"]',
    "hero.cta1"       : "Voir mes projets",
    "hero.cta2"       : "Télécharger mon CV",
    "hero.stat1"      : "Projets réalisés",
    "hero.stat2"      : "Mois de stage",
    "hero.stat3"      : "Technologies",
    "qnav.about"      : "À propos",
    "qnav.about.sub"  : "Mon profil, mes langues, mes loisirs",
    "qnav.skills"     : "Compétences",
    "qnav.skills.sub" : "Mes langages et outils maîtrisés",
    "qnav.projects"   : "Projets",
    "qnav.projects.sub":"Réalisations scolaires et perso",
    "qnav.parcours"   : "Parcours",
    "qnav.parcours.sub":"Formation et expériences pro",

    /* ABOUT */
    "about.title"     : "À propos de moi",
    "about.subtitle"  : "Étudiant en reconversion passionné par le développement",
    "about.bio1"      : "Passionné par l'informatique depuis toujours, j'ai d'abord été autodidacte avant de décider de reprendre mes études. Je suis actuellement en BTS SIO option SLAM à l'AFTEC de Vannes, en reconversion professionnelle.",
    "about.bio2"      : "Pendant ma Licence Mathématiques Informatique à l'UBS, j'ai découvert la programmation orientée objet avec Java, Python, la logique avec SwiProlog, et le développement web. Mon stage à la DSDEN du Morbihan m'a permis d'appliquer ces compétences en situation réelle.",
    "about.bio3"      : "Mon objectif : rejoindre une équipe dynamique en alternance pour développer mes compétences et contribuer à des projets concrets.",
    "about.who"           : "Qui suis-je ?",
    "about.languages.title": "Langues",
    "about.native"        : "Langue maternelle",
    "about.intermediate"  : "Niveau intermédiaire",
    "about.softskills"    : "Savoir-être",
    "about.soft.reactive" : "Réactif",
    "about.soft.proactive": "Proactif",
    "about.soft.ideas"    : "Force de proposition",
    "about.soft.teamwork" : "Esprit d'équipe",
    "about.soft.motivated": "Motivé",
    "about.soft.adaptable": "Adaptable",
    "about.hobbies"           : "Centres d'intérêt",
    "about.badminton.desc"    : "Pratique compétitive — 10 ans",
    "about.piano.desc"        : "10 ans de pratique",
    "about.escalade.desc"     : "3 ans de pratique",
    "about.voyages.desc"      : "Écosse, Espagne, Angleterre, Portugal",
    "about.license"           : "Permis B — véhiculé",
    "about.age"               : "27 ans",

    /* SKILLS */
    "skills.title"    : "Mes compétences",
    "skills.subtitle" : "Langages, frameworks et outils que j'utilise",
    "skills.label"    : "Stack technique",
    "skills.db"       : "Bases de données",
    "skills.tools"    : "Outils & Systèmes",
    "skills.methods"  : "Méthodologies & Environnements",
    "skills.modding"  : "Modding Minecraft",

    /* PROJECTS */
    "projects.title"   : "Mes projets",
    "projects.subtitle": "Réalisations réalisées pendant mes études et en stage",
    "projects.label"   : "Réalisations",
    "filter.all"       : "Tous",
    "filter.web"       : "Web",
    "filter.java"      : "Java",
    "filter.network"   : "Réseau",
    "filter.python"    : "Python",
    "filter.stage"     : "Stage",
    "filter.game"      : "Jeux / Mods",
    "proj.drasi.type"  : "Stage · BTS SIO · DSDEN Morbihan",
    "proj.drasi.desc"  : "Site portfolio de l'équipe académique de Vannes (DSII). HTML/CSS/JS, conforme charte graphique de l'académie de Rennes.",
    "proj.grr.desc"    : "Déploiement et configuration d'un système GRR sur WAMP pour la réservation de ressources informatiques en réseau interne.",
    "proj.nommage.desc": "Outil de nommage automatique des postes informatiques via Grist + Python/PowerShell. Priorité haute — avant c'était fait à la main.",
    "proj.remp.desc"   : "Service Grist pour centraliser les remplacements des enseignants du 1er degré. Remplace les échanges Excel/mail des circonscriptions.",
    "proj.mangatec.desc": "Application web de gestion d'une médiathèque de mangas. CRUD complet, auth, rôles, interface responsive. Projet BTS SIO SLAM.",
    "proj.portfolio.desc": "Ce portfolio ! Multi-pages, responsive, bilingue FR/EN, animations CSS au scroll, zéro framework.",
    "proj.splendor.desc": "Implémentation complète du jeu de société Splendor en Java. Gestion des joueurs, cartes, jetons, nobles et IA simple.",
    "proj.isle.desc"   : "Mod Minecraft inspiré de \"Dragons\" (How to Train Your Dragon). Ajout de dragons apprivoisables, nouvelles îles, mécaniques de vol et de combat.",
    "proj.money.desc"  : "Mod Minecraft ajoutant un système économique complet : monnaie, marchands, transactions entre joueurs et économie in-game.",
    "proj.inprogress"  : "En cours",
    "proj.personal"    : "Perso",
    "tag.team"         : "En équipe",
    "tag.stage.bts"    : "Stage BTS SIO",

    /* SHARED PROJECT H3 HEADINGS */
    "proj.h3.context"     : "Contexte",
    "proj.h3.context.pb"  : "Contexte & problème",
    "proj.h3.overview"    : "Présentation",
    "proj.h3.features"    : "Fonctionnalités",
    "proj.h3.tech"        : "Architecture technique",
    "proj.h3.learning"    : "Ce que j'ai appris",
    "proj.h3.results"     : "Résultat",
    "proj.h3.screenshots" : "Aperçus du projet",
    "proj.h3.skills"      : "Compétences validées",

    /* SHARED SIDEBAR */
    "proj.sidebar.infos"       : "Infos projet",
    "proj.sidebar.stack"       : "Stack",
    "proj.sidebar.other.stage" : "Autres projets de stage",
    "proj.sidebar.other.mod"   : "Autre mod",
    "proj.sidebar.all"         : "← Tous les projets",
    "proj.back"                : "← Retour aux projets",

    /* ── STAGE DRASI ── */
    "proj.drasi.h3.pages"     : "Pages réalisées",
    "proj.drasi.h3.technical" : "Points techniques notables",
    "proj.drasi.h3.security"  : "Sécurité",
    "proj.drasi.context.p1"   : "Développé lors d'un stage de 6 semaines à la DSDEN du Morbihan, ce site a été réalisé en binôme (deux stagiaires BTS SIO) sous la supervision du Responsable DSI. Le projet constitue le Dossier E5 du BTS SIO SLAM.",
    "proj.drasi.context.p2"   : "Objectif : créer un site vitrine 100% statique (HTML/CSS/JS vanilla + PHP pour le formulaire) présentant l'équipe, les missions, le périmètre d'intervention et les services de la DRASI. Conformité obligatoire avec la charte graphique de l'Académie de Rennes.",
    "proj.drasi.page.1"       : "Accueil — présentation générale de la DRASI",
    "proj.drasi.page.2"       : "Notre histoire — historique du service (ex-DSII)",
    "proj.drasi.page.3"       : "Nos équipes — membres et rôles",
    "proj.drasi.page.4"       : "Nos missions — périmètre d'intervention",
    "proj.drasi.page.5"       : "Notre périmètre — carte interactive (Leaflet.js)",
    "proj.drasi.page.6"       : "Services opérés — liste des services gérés",
    "proj.drasi.page.7"       : "Comitologie — gouvernance",
    "proj.drasi.page.8"       : "Nous contacter — formulaire sécurisé (reCAPTCHA v2 + PHP)",
    "proj.drasi.tech.1"       : "Architecture composants : header, footer et cookie banner chargés via fetch() pour éviter la duplication",
    "proj.drasi.tech.2"       : "Carte interactive du périmètre géographique avec Leaflet.js",
    "proj.drasi.tech.3"       : "Formulaire de contact sécurisé : reCAPTCHA v2, validation PHP côté serveur, envoi par mail()",
    "proj.drasi.tech.4"       : "Système d'analytics maison (RGPD-compliant) : pages visitées, temps passé, sources — stockage localStorage, export CSV",
    "proj.drasi.tech.5"       : "Conformité charte graphique Académie de Rennes (couleurs, typos, logo Marianne)",
    "proj.drasi.tech.6"       : "Tests multi-navigateurs : Chrome, Firefox, Edge, Safari — audit Lighthouse",
    "proj.drasi.tech.7"       : "Déploiement Apache 2.4 Linux en production, versionné sur GitHub",
    "proj.drasi.tech.8"       : "Accessibilité : balises sémantiques, contrastes WCAG, navigation clavier",
    "proj.drasi.sec.1"        : "HTTPS avec certificat SSL, cookies httpOnly + SameSite",
    "proj.drasi.sec.2"        : "Headers Apache : X-Frame-Options, X-XSS-Protection, Content-Security-Policy",
    "proj.drasi.sec.3"        : "reCAPTCHA v2 sur le formulaire de contact",
    "proj.drasi.sec.4"        : "Validation double : client (HTML5) + serveur (PHP)",
    "proj.drasi.meta.date"    : "Déc. 2024 – Jan. 2025 (6 sem.)",
    "proj.drasi.meta.org"     : "DSDEN du Morbihan — DRASI",
    "proj.drasi.meta.location": "Vannes (56)",
    "proj.drasi.meta.team"    : "2 stagiaires BTS SIO",
    "proj.drasi.meta.client"  : "Commanditaire : Responsable DSI",
    "proj.drasi.meta.dossier" : "Dossier E5 — BTS SIO SLAM",

    /* ── STAGE GRR ── */
    "proj.grr.h3.done"        : "Ce que j'ai fait",
    "proj.grr.h3.troubleshoot": "Dépannage résolu",
    "proj.grr.context.p1"     : "La DSDEN du Morbihan avait besoin d'un système centralisé pour que les équipes puissent réserver du matériel informatique (salles, équipements) sans passer par des échanges informels. J'ai déployé et configuré le logiciel open-source GRR (Gestion et Réservation de Ressources).",
    "proj.grr.result.p1"      : "Le GRR est accessible depuis tous les postes du réseau interne via http://infra56/reservations. Un guide d'installation complet a été remis pour faciliter la reprise du service.",
    "proj.grr.done.1"         : "Installation et configuration de WAMP Server sur Windows 11 (serveur local)",
    "proj.grr.done.2"         : "Installation des prérequis Visual C++ Redistributable",
    "proj.grr.done.3"         : "Déploiement de GRR depuis GitHub (JeromeDevome/GRR) dans le répertoire /reservations",
    "proj.grr.done.4"         : "Création de la base de données MySQL grr via phpMyAdmin",
    "proj.grr.done.5"         : "Configuration Apache pour accès réseau : modification de httpd.conf et des VirtualHosts",
    "proj.grr.done.6"         : "Ouverture du pare-feu Windows sur le port 80 (TCP)",
    "proj.grr.done.7"         : "Configuration du fichier hosts pour nommage interne : infra56/reservations",
    "proj.grr.done.8"         : "Rédaction d'un guide d'installation complet pour la reprise et maintenance",
    "proj.grr.fix.1"          : "Port 80 occupé (Skype, IIS) → identification et libération du port",
    "proj.grr.fix.2"          : "Erreur 403 Apache → correction des droits d'accès (Require all granted)",
    "proj.grr.fix.3"          : "Accès réseau impossible → configuration VirtualHost + règles pare-feu",
    "proj.grr.meta.date"      : "2024–2025",
    "proj.grr.meta.org"       : "DSDEN du Morbihan",
    "proj.grr.meta.location"  : "Vannes (56)",
    "proj.grr.meta.dossier"   : "BTS SIO SLAM — AFTEC",
    "proj.grr.meta.deliverable": "Livrables : GRR opérationnel + documentation",

    /* ── STAGE NOMMAGE ── */
    "proj.nommage.h3.done"    : "Ce que j'ai réalisé",
    "proj.nommage.h3.formula" : "La formule Python (Grist)",
    "proj.nommage.context.p1" : "Les techniciens de la DSDEN nommaient manuellement chaque nouveau poste informatique lors de son intégration au réseau. Cette opération était source d'erreurs (fautes de frappe, doublons, incohérences avec l'inventaire). Le service avait besoin d'un outil automatisé respectant les conventions de nommage de l'Éducation Nationale.",
    "proj.nommage.context.p2" : "Projet réalisé en binôme avec un autre stagiaire, sous la direction du Responsable Adjoint DSI. Priorité haute — service qui n'existait pas auparavant.",
    "proj.nommage.formula.p1" : "Le cœur du projet est une formule Python écrite directement dans Grist. Elle construit le nom du poste en :",
    "proj.nommage.done.1"     : "Apprentissage de Grist — outil de base de données collaboratif hébergé sur Toutatice (EN)",
    "proj.nommage.done.2"     : "Conception des tables de référence : OS, modèles matériels, circonscriptions, EPLE, département",
    "proj.nommage.done.3"     : "Développement du formulaire de saisie Grist accessible aux techniciens",
    "proj.nommage.done.4"     : "Formule Python dans Grist (generer_code_resu()) pour générer automatiquement un nom unique",
    "proj.nommage.done.5"     : "Logique d'incrémentation : le nom généré intègre le département, l'identifiant de circonscription et un numéro séquentiel auto-incrémenté sans doublon",
    "proj.nommage.done.6"     : "Export CSV compatible MDT Web pour le déploiement Windows",
    "proj.nommage.done.7"     : "Tests sur poste dédié, sessions de test par types d'utilisateurs",
    "proj.nommage.done.8"     : "Documentation technique et guide utilisateur",
    "proj.nommage.formula.1"  : "Récupérant le numéro de département (56) et le nom de la circonscription",
    "proj.nommage.formula.2"  : "Extrayant les 3 derniers caractères du nom de circonscription et l'identifiant entre parenthèses",
    "proj.nommage.formula.3"  : "Parcourant toutes les entrées existantes pour collecter les numéros déjà utilisés dans le même groupe (même département + même circonscription)",
    "proj.nommage.formula.4"  : "Attribuant le plus petit numéro disponible (1–99, formaté en 2 chiffres)",
    "proj.nommage.formula.5"  : "Retournant le nom final : 56-XXX-IDEN-01",
    "proj.nommage.meta.date"  : "Juillet 2025 (~10 jours)",
    "proj.nommage.meta.org"   : "DSDEN du Morbihan — DSI",
    "proj.nommage.meta.team"  : "2 stagiaires + Responsable Adjoint DSI",
    "proj.nommage.meta.priority": "Priorité haute",
    "proj.nommage.meta.dossier": "BTS SIO SLAM — AFTEC",

    /* ── STAGE REMP ── */
    "proj.remp.h3.done"       : "Ce qui a été réalisé",
    "proj.remp.h3.notdone"    : "Ce qui n'a pas pu être livré",
    "proj.remp.unfinished.title": "Projet inachevé",
    "proj.remp.unfinished.p1" : "Ce projet n'a pas pu être finalisé en raison de contraintes budgétaires et matérielles du service commanditaire. La conception et l'architecture ont été livrées, mais le déploiement complet n'a pas pu être effectué dans les délais du stage.",
    "proj.remp.context.p1"    : "Les circonscriptions géraient les remplacements d'enseignants via des échanges de mails quotidiens et des fichiers Excel. Ce système était chronophage, sujet aux erreurs et difficile à suivre pour la direction générale.",
    "proj.remp.context.p2"    : "Projet réalisé en binôme (deux stagiaires BTS SIO) sous la direction du Responsable Adjoint DSI. La deadline était le départ du commanditaire (juillet 2025).",
    "proj.remp.learning.p1"   : "Au-delà des aspects techniques, ce projet m'a confronté à la réalité des projets en entreprise : les contraintes budgétaires et organisationnelles peuvent bloquer un projet techniquement viable. Gestion des priorités, communication avec le commanditaire, adaptation face aux imprévus.",
    "proj.remp.done.1"        : "Analyse des besoins avec le commanditaire (Responsable DSI)",
    "proj.remp.done.2"        : "Conception de l'architecture de données dans Grist",
    "proj.remp.done.3"        : "Création des tables de référence (circonscriptions, BD, départements)",
    "proj.remp.done.4"        : "Formulaires de saisie par circonscription",
    "proj.remp.done.5"        : "Structure de la table synthèse pour la direction générale",
    "proj.remp.done.6"        : "Prototype de gestion des droits utilisateurs",
    "proj.remp.done.7"        : "Documentation technique partielle et guide utilisateur",
    "proj.remp.notdone.1"     : "Déploiement complet sur l'infrastructure Toutatice de l'EN",
    "proj.remp.notdone.2"     : "Intégration avec les outils existants (manque de ressources matérielles)",
    "proj.remp.notdone.3"     : "Tests utilisateurs avec le personnel des circonscriptions",
    "proj.remp.notdone.4"     : "Recette finale par le commanditaire",
    "proj.remp.meta.date"     : "Juillet 2025 (~13 jours prévus)",
    "proj.remp.meta.org"      : "DSDEN du Morbihan — DSI",
    "proj.remp.meta.team"     : "2 stagiaires BTS SIO",
    "proj.remp.meta.priority" : "Priorité haute — inachevé",
    "proj.remp.meta.stop"     : "Arrêt : contraintes budgétaires et matérielles",
    "proj.remp.meta.dossier"  : "BTS SIO SLAM — AFTEC",
    "proj.remp.sidebar.stack" : "Stack prévue",

    /* ── MANGATEC ── */
    "proj.mangatec.h3.context"  : "Contexte & objectifs",
    "proj.mangatec.h3.features" : "Fonctionnalités réalisées",
    "proj.mangatec.h3.roles"    : "Gestion des rôles (Spatie Laravel Permission)",
    "proj.mangatec.h3.tech"     : "Architecture technique",
    "proj.mangatec.h3.infra"    : "Infrastructure virtualisée",
    "proj.mangatec.h3.learning" : "Ce que j'ai appris",
    "proj.mangatec.context.p1"  : "Mangatec est une application web de gestion d'une médiathèque spécialisée dans les mangas (comics japonais). Ce projet constitue le Dossier E6 du BTS SIO SLAM, réalisé à l'AFTEC de Vannes.",
    "proj.mangatec.context.p2"  : "L'objectif était de concevoir et déployer une application complète permettant aux membres d'une médiathèque de consulter et gérer le catalogue de mangas, avec des droits différenciés selon le rôle de l'utilisateur.",
    "proj.mangatec.roles.p1"    : "Trois niveaux d'accès distincts, gérés via le package Spatie Laravel Permission :",
    "proj.mangatec.infra.p1"    : "Le projet a été déployé en environnement virtualisé, reproduisant une architecture client/serveur réelle :",
    "proj.mangatec.feat.1"      : "UC1 — Authentification : inscription, connexion, déconnexion sécurisées (Laravel Breeze / Auth)",
    "proj.mangatec.feat.2"      : "UC2 — Consultation du catalogue : liste des mangas, recherche par titre / auteur / genre, affichage détaillé",
    "proj.mangatec.feat.3"      : "UC3 — Gestion du catalogue (modérateur / admin) : ajout, modification, suppression de mangas et de séries",
    "proj.mangatec.feat.4"      : "UC4 — Administration (admin uniquement) : gestion des utilisateurs, attribution des rôles, supervision",
    "proj.mangatec.role.1"      : "User — consultation uniquement : lecture du catalogue, recherche",
    "proj.mangatec.role.2"      : "Modérateur — gestion éditoriale : ajout et modification des fiches mangas, gestion du catalogue",
    "proj.mangatec.role.3"      : "Administrateur — contrôle total : gestion des utilisateurs, attribution des rôles, administration complète",
    "proj.mangatec.tech.1"      : "Framework : Laravel 11 — architecture MVC, routes nommées, middlewares",
    "proj.mangatec.tech.2"      : "Backend : PHP 8.2 — Eloquent ORM, relations Many-to-Many (mangas ↔ genres), migrations, seeders",
    "proj.mangatec.tech.3"      : "Base de données : MySQL 8.0 — schéma relationnel complet",
    "proj.mangatec.tech.4"      : "Templates : Blade — composants réutilisables, layouts partagés",
    "proj.mangatec.tech.5"      : "Permissions : Spatie Laravel Permission — rôles et permissions en base de données",
    "proj.mangatec.infra.1"     : "VM Serveur (Ubuntu Server) : Apache2, PHP 8.2, MySQL 8.0, application Laravel",
    "proj.mangatec.infra.2"     : "VM Client (Ubuntu Desktop) : accès à l'application via navigateur",
    "proj.mangatec.infra.3"     : "Connexion réseau local entre les VMs — simulation d'un environnement de production",
    "proj.mangatec.learn.1"     : "Prise en main de Laravel 11 : routing, controllers, models, Eloquent",
    "proj.mangatec.learn.2"     : "Gestion des rôles et permissions avec Spatie — séparation nette des droits",
    "proj.mangatec.learn.3"     : "Conception de schémas relationnels et migrations",
    "proj.mangatec.learn.4"     : "Déploiement sur Apache Linux en environnement virtualisé",
    "proj.mangatec.learn.5"     : "Rédaction de documentation technique (Dossier E6 BTS SIO)",
    "proj.mangatec.meta.date"   : "2024 – 2025",
    "proj.mangatec.meta.school" : "AFTEC Vannes",
    "proj.mangatec.meta.dossier": "Dossier E6 — BTS SIO SLAM",
    "proj.mangatec.meta.team"   : "Projet individuel",
    "proj.mangatec.meta.infra"  : "2 VMs Ubuntu (client + serveur)",

    /* ── PORTFOLIO ── */
    "proj.portfolio.h3.overview" : "Présentation",
    "proj.portfolio.h3.features" : "Fonctionnalités",
    "proj.portfolio.h3.tech"     : "Choix techniques",
    "proj.portfolio.overview.p1" : "Ce portfolio est l'un des projets phares du BTS SIO SLAM. Il a pour but de présenter mon profil, mes compétences et mes réalisations à de futurs employeurs ou recruteurs.",
    "proj.portfolio.overview.p2" : "Développé entièrement en HTML, CSS et JavaScript vanilla (sans framework), il met en œuvre des bonnes pratiques modernes du développement web.",
    "proj.portfolio.feat.1"      : "Architecture multi-pages avec navigation cohérente",
    "proj.portfolio.feat.2"      : "Design responsive (mobile, tablette, desktop)",
    "proj.portfolio.feat.3"      : "Système de traduction bilingue FR/EN (localStorage)",
    "proj.portfolio.feat.4"      : "Animations au scroll (Intersection Observer API)",
    "proj.portfolio.feat.5"      : "Animations de barres de compétences",
    "proj.portfolio.feat.6"      : "Filtre des projets par catégorie",
    "proj.portfolio.feat.7"      : "Animation de typing dans le hero",
    "proj.portfolio.feat.8"      : "Menu hamburger pour mobile",
    "proj.portfolio.feat.9"      : "Bannière de gestion des cookies",
    "proj.portfolio.feat.10"     : "Aperçu et téléchargement du CV PDF",
    "proj.portfolio.tech.1"      : "Zéro dépendance : HTML/CSS/JS pur, pas de framework",
    "proj.portfolio.tech.2"      : "CSS custom properties (variables) pour la cohérence visuelle",
    "proj.portfolio.tech.3"      : "Google Fonts (Inter + JetBrains Mono)",
    "proj.portfolio.tech.4"      : "Thème sombre inspiré des interfaces de développeur",
    "proj.portfolio.tech.5"      : "Accessibilité : balises sémantiques, aria-labels, focus visible",
    "proj.portfolio.sidebar.info": "Informations",
    "proj.portfolio.meta.date"   : "2024 – 2026 (en cours)",
    "proj.portfolio.meta.school" : "AFTEC Vannes",
    "proj.portfolio.meta.bts"    : "BTS SIO SLAM",
    "proj.portfolio.meta.team"   : "Projet individuel",
    "proj.portfolio.sidebar.tech": "Technologies",
    "proj.portfolio.cta.view"    : "Voir le portfolio",

    /* ── SPLENDOR ── */
    "proj.splendor.h3.context"   : "Contexte",
    "proj.splendor.h3.game"      : "Le jeu Splendor",
    "proj.splendor.h3.developed" : "Ce que nous avons développé",
    "proj.splendor.h3.skills"    : "Compétences validées",
    "proj.splendor.context.p1"   : "Ce projet a été réalisé en fin de 2ème année de Licence Mathématiques Informatique à l'UBS de Vannes, en équipe de trois. Il constituait le projet de validation des acquis en programmation Java, avec une soutenance orale finale devant un jury pour présenter les choix techniques et démontrer le fonctionnement du jeu.",
    "proj.splendor.context.p2"   : "L'objectif : implémenter le jeu de plateau Splendor en Java de A à Z — des règles du jeu jusqu'à l'interface CLI jouable, en passant par la gestion complète des états de partie.",
    "proj.splendor.game.p1"      : "Splendor est un jeu de stratégie où les joueurs collectent des jetons représentant des gemmes précieuses pour acheter des cartes de développement. Ces cartes permettent d'acquérir des cartes plus puissantes et d'attirer des nobles pour marquer des points de prestige. Le premier joueur à atteindre 15 points de prestige remporte la partie.",
    "proj.splendor.dev.1"        : "Modélisation complète des entités : joueurs, cartes (3 niveaux), jetons (5 gemmes + joker), nobles",
    "proj.splendor.dev.2"        : "Gestion du plateau : piles par niveau, pioche, réservation des cartes",
    "proj.splendor.dev.3"        : "Logique de jeu complète : collecte de jetons (règles de limite), achat de cartes, réservation, attraction des nobles",
    "proj.splendor.dev.4"        : "Système de scoring et détection de fin de partie (15 pts, dernier tour complet)",
    "proj.splendor.dev.5"        : "Interface en ligne de commande (CLI) lisible et jouable à 2–4 joueurs",
    "proj.splendor.dev.6"        : "Gestion des tours et validation des actions illégales",
    "proj.splendor.skill.1"      : "Programmation orientée objet : héritage, encapsulation, polymorphisme, interfaces",
    "proj.splendor.skill.2"      : "Conception d'architecture Java multi-classes et multi-packages",
    "proj.splendor.skill.3"      : "Algorithmique : machine à états, boucle de jeu, gestion des cas limites",
    "proj.splendor.skill.4"      : "Travail en équipe, répartition des tâches, versioning avec Git",
    "proj.splendor.skill.5"      : "Communication technique : soutenance orale et défense des choix de conception",
    "proj.splendor.meta.date"    : "Fin 2ème année Licence (2023)",
    "proj.splendor.meta.school"  : "UBS Vannes",
    "proj.splendor.meta.degree"  : "Licence Mathématiques Informatique",
    "proj.splendor.meta.team"    : "Projet en trio",
    "proj.splendor.meta.defence" : "Soutenance orale devant jury",

    /* ── ISLE OF BERK ── */
    "proj.isle.h3.overview"      : "Présentation",
    "proj.isle.h3.features"      : "Fonctionnalités prévues / en cours",
    "proj.isle.h3.learning"      : "Ce que ça m'apporte techniquement",
    "proj.isle.h3.status"        : "Statut actuel",
    "proj.isle.overview.p1"      : "Isle of Berk est un projet personnel de mod Minecraft développé en Java avec l'API Minecraft Forge. Il s'inspire directement de l'univers de la franchise DreamWorks Dragons (Comment dresser votre dragon) — dragons à apprivoiser, l'île de Beurk (Berk), personnages emblématiques.",
    "proj.isle.overview.p2"      : "Ce projet me permet d'approfondir ma maîtrise de la programmation orientée objet en Java dans un contexte concret et stimulant, tout en explorant les API Forge pour créer du contenu de jeu original.",
    "proj.isle.status.p1"        : "Le projet est en développement actif. Les premières entités de dragons sont en cours d'implémentation avec leur système de comportement de base.",
    "proj.isle.feat.1"           : "Ajout de plusieurs espèces de dragons (entités personnalisées)",
    "proj.isle.feat.2"           : "Système d'apprivoisement et de montée en confiance",
    "proj.isle.feat.3"           : "Mécanique de vol sur le dos des dragons",
    "proj.isle.feat.4"           : "Attaques spéciales par espèce (feu, plasma, etc.)",
    "proj.isle.feat.5"           : "Nouvelles îles générées procéduralement",
    "proj.isle.feat.6"           : "Nouveau biome inspiré de l'archipel nordique",
    "proj.isle.feat.7"           : "Craft d'équipements et de selles pour dragons",
    "proj.isle.feat.8"           : "PNJ (personnages du film) avec dialogues",
    "proj.isle.learn.1"          : "Maîtrise avancée des patterns OOP en Java (héritage, interfaces, génériques)",
    "proj.isle.learn.2"          : "Compréhension de l'API Forge : registres, events, renderers",
    "proj.isle.learn.3"          : "Gestion d'entités complexes (IA, pathfinding, états)",
    "proj.isle.learn.4"          : "Travail avec des fichiers JSON (modèles 3D, recettes)",
    "proj.isle.learn.5"          : "Gestion de projet en solo avec versioning Git",
    "proj.isle.meta.date"        : "En cours",
    "proj.isle.meta.type"        : "Projet personnel",
    "proj.isle.meta.team"        : "Solo",
    "proj.isle.meta.target"      : "Minecraft Java Edition",
    "proj.isle.wip"              : "En cours de développement",

    /* ── MONEY MOD ── */
    "proj.money.h3.overview"     : "Présentation",
    "proj.money.h3.features"     : "Fonctionnalités",
    "proj.money.h3.tech"         : "Architecture technique",
    "proj.money.h3.learning"     : "Ce que ça m'apporte",
    "proj.money.overview.p1"     : "Money Mod ajoute à Minecraft un vrai système économique qui n'existe pas nativement dans le jeu. L'idée de départ : permettre aux joueurs d'un serveur de commercer de manière structurée, avec une monnaie physique (pièces craftables) et des marchands PNJ.",
    "proj.money.feat.1"          : "Ajout de pièces de monnaie (bronze, argent, or) — items craftables",
    "proj.money.feat.2"          : "Système de portefeuille par joueur (stockage de monnaie)",
    "proj.money.feat.3"          : "Marchands PNJ avec catalogue d'achats/ventes configurable",
    "proj.money.feat.4"          : "Transactions joueur-à-joueur via commandes ou interface",
    "proj.money.feat.5"          : "Historique des transactions (log)",
    "proj.money.feat.6"          : "Équilibrage économique configurable (taux de change, prix)",
    "proj.money.tech.1"          : "Items personnalisés (pièces) avec logique de craft",
    "proj.money.tech.2"          : "Entités marchands avec inventaire et IA de base",
    "proj.money.tech.3"          : "Système de sauvegarde de données joueur (NBT / JSON)",
    "proj.money.tech.4"          : "Commandes custom enregistrées via Forge",
    "proj.money.tech.5"          : "Gestion des events Forge (interaction joueur, craft...)",
    "proj.money.learn.1"         : "Pratique de la gestion de données persistantes en Java",
    "proj.money.learn.2"         : "Conception d'un système complexe avec de nombreuses interactions",
    "proj.money.learn.3"         : "Expérience avec les registres Forge et le cycle de vie du mod",
    "proj.money.learn.4"         : "Pensée systémique : équilibrage et cohérence économique",
    "proj.money.meta.type"       : "Projet personnel",
    "proj.money.meta.team"       : "Solo",
    "proj.money.meta.target"     : "Minecraft Java Edition",
    "proj.money.meta.api"        : "Minecraft Forge API",

    /* PARCOURS */
    "parcours.title"    : "Mon parcours",
    "parcours.subtitle" : "Formation académique et expériences professionnelles",
    "parcours.label"    : "Qui je suis",
    "parcours.edu"      : "📚 Formation",
    "parcours.exp"      : "💼 Expériences",
    "parcours.inprogress": "En cours",
    "parcours.bts.desc" : "Formation en Solutions Logicielles et Applications Métiers. Développement web (Laravel, PHP, HTML/CSS/JS), bases de données, réseaux, méthodes agiles. Stage de 10 semaines cumulées à la DSDEN du Morbihan.",
    "parcours.licence.desc": "Programmation orientée objet Java, algorithmique, Python, SwiProlog, développement web (HTML/CSS/PHP/JS), bases de données SQL. Projets notables : jeu Splendor en Java (projet de 2ème année, en trio, soutenance orale), Jeu de la vie Conway, TP web.",
    "parcours.stage.desc": "10 semaines cumulées. Développement d'un site vitrine institutionnel, déploiement d'un GRR (gestionnaire de réservations), outil de nommage automatique des postes (Grist + Python), service de gestion des remplacements (REMP).",
    "parcours.caisse.desc": "Gestion de rayon, encaissement, relation client. Poste occupé en parallèle de la reprise d'études.",
    "parcours.rayon.desc": "Accueil client, mise en rayon multi-rayons, gestion des imprévus. Expérience de 2 ans en parallèle des études.",
    "parcours.cta.cv"   : "Télécharger mon CV",
    "parcours.cta.contact": "Me contacter",

    /* CONTACT */
    "contact.label"       : "Prenons contact",
    "contact.title"       : "Me contacter",
    "contact.subtitle"    : "Une question, une opportunité d'alternance ? Écrivez-moi directement.",
    "contact.phone"       : "Téléphone",
    "contact.location"    : "Localisation",
    "contact.mobility"    : "Mobilité",
    "contact.availability": "Disponibilité",
    "contact.license"     : "Permis B — véhiculé",
    "contact.available"   : "En recherche d'alternance — contrat éligible aide de 5 000 €",
    "contact.dl.cv"       : "⬇ Télécharger mon CV",
    "form.name"           : "Votre nom",
    "form.company"        : "Entreprise (optionnel)",
    "form.email.label"    : "Votre adresse email",
    "form.subject"        : "Objet",
    "form.message"        : "Message",
    "form.name.ph"        : "Jean Dupont",
    "form.company.ph"     : "Nom de l'entreprise",
    "form.subject.ph"     : "Proposition d'alternance, question...",
    "form.message.ph"     : "Votre message...",
    "form.notice"         : "Ce formulaire ouvre votre client mail (Outlook, Thunderbird, Gmail...) avec les informations pré-remplies.",
    "form.submit"         : "Envoyer le message →",
    "form.success"        : "✓ Votre client mail a été ouvert avec le message pré-rempli.",

    /* CV */
    "cv.title"    : "Mon CV",
    "cv.subtitle" : "Téléchargez mon curriculum vitae complet",
    "cv.download" : "Télécharger le CV (PDF)",
    "cv.view"     : "Voir en plein écran",

    /* COOKIE */
    "cookie.title"  : "Gestion des cookies",
    "cookie.text"   : "Ce site utilise localStorage pour mémoriser vos préférences (langue, cookie). Aucune donnée personnelle n'est collectée ni transmise.",
    "cookie.accept" : "Accepter",
    "cookie.refuse" : "Refuser",

    /* FOOTER */
    "footer.copy"   : "Jean-Baptiste Noblet — Portfolio",
    "footer.made"   : "Fait avec HTML / CSS / JS",
  },

  en: {
    /* NAV */
    "nav.home"        : "Home",
    "nav.about"       : "About",
    "nav.skills"      : "Skills",
    "nav.projects"    : "Projects",
    "nav.parcours"    : "Background",
    "nav.cv"          : "Resume",
    "nav.contact"     : "Contact",

    /* INDEX */
    "hero.label"      : "Welcome to my portfolio",
    "hero.subtitle"   : "Web & Software Developer",
    "hero.typing"     : '["BTS SIO SLAM Student","Aspiring Developer","Tech Enthusiast","Looking for apprenticeship"]',
    "hero.cta1"       : "See my projects",
    "hero.cta2"       : "Download my resume",
    "hero.stat1"      : "Projects completed",
    "hero.stat2"      : "Months of internship",
    "hero.stat3"      : "Technologies",
    "qnav.about"      : "About",
    "qnav.about.sub"  : "My profile, languages, hobbies",
    "qnav.skills"     : "Skills",
    "qnav.skills.sub" : "Languages and tools I master",
    "qnav.projects"   : "Projects",
    "qnav.projects.sub":"Academic and personal projects",
    "qnav.parcours"   : "Background",
    "qnav.parcours.sub":"Education and professional experience",

    /* ABOUT */
    "about.title"     : "About me",
    "about.subtitle"  : "Career-changing student passionate about development",
    "about.bio1"      : "Passionate about computing since day one, I was first self-taught before deciding to go back to school. I'm currently studying BTS SIO SLAM at AFTEC in Vannes, as a career changer.",
    "about.bio2"      : "During my Mathematics & Computer Science degree at UBS, I discovered OOP with Java, Python, logic programming with SwiProlog, and web development. My internship at DSDEN du Morbihan let me apply these skills in a real professional context.",
    "about.bio3"      : "My goal: join a dynamic team as an apprentice to develop my skills and contribute to real-world projects.",
    "about.who"           : "Who am I?",
    "about.languages.title": "Languages",
    "about.native"        : "Native language",
    "about.intermediate"  : "Intermediate level",
    "about.softskills"    : "Soft skills",
    "about.soft.reactive" : "Responsive",
    "about.soft.proactive": "Proactive",
    "about.soft.ideas"    : "Full of ideas",
    "about.soft.teamwork" : "Team player",
    "about.soft.motivated": "Motivated",
    "about.soft.adaptable": "Adaptable",
    "about.hobbies"           : "Interests",
    "about.badminton.desc"    : "Competitive practice — 10 years",
    "about.piano.desc"        : "10 years of practice",
    "about.escalade.desc"     : "3 years of practice",
    "about.voyages.desc"      : "Scotland, Spain, England, Portugal",
    "about.license"           : "Driving license B — own vehicle",
    "about.age"               : "27 years old",

    /* SKILLS */
    "skills.title"    : "My skills",
    "skills.subtitle" : "Languages, frameworks and tools I use",
    "skills.label"    : "Tech stack",
    "skills.db"       : "Databases",
    "skills.tools"    : "Tools & Systems",
    "skills.methods"  : "Methodologies & Environments",
    "skills.modding"  : "Minecraft Modding",

    /* PROJECTS */
    "projects.title"   : "My projects",
    "projects.subtitle": "Projects built during my studies and internship",
    "projects.label"   : "Work",
    "filter.all"       : "All",
    "filter.web"       : "Web",
    "filter.java"      : "Java",
    "filter.network"   : "Network",
    "filter.python"    : "Python",
    "filter.stage"     : "Internship",
    "filter.game"      : "Games / Mods",
    "proj.drasi.type"  : "Internship · BTS SIO · DSDEN Morbihan",
    "proj.drasi.desc"  : "Portfolio website for the academic team of Vannes (DSII). HTML/CSS/JS, compliant with the Rennes academy's graphic charter.",
    "proj.grr.desc"    : "Deployment and configuration of a GRR room-booking system on WAMP for internal network IT resource reservations.",
    "proj.nommage.desc": "Automatic computer naming tool via Grist + Python/PowerShell. High priority — previously done manually.",
    "proj.remp.desc"   : "Grist service to centralise substitute teacher management for primary schools. Replaces Excel/email exchanges between districts.",
    "proj.mangatec.desc": "Web app for managing a manga media library. Full CRUD, authentication, roles, responsive UI. BTS SIO SLAM project.",
    "proj.portfolio.desc": "This portfolio! Multi-page, responsive, bilingual FR/EN, CSS scroll animations, zero framework.",
    "proj.splendor.desc": "Full implementation of the Splendor board game in Java. Player management, cards, tokens, nobles and simple AI.",
    "proj.isle.desc"   : "Minecraft mod inspired by How to Train Your Dragon. Adds tameable dragons, new islands, flight and combat mechanics.",
    "proj.money.desc"  : "Minecraft mod adding a full economy system: currency, merchants, player transactions and in-game economy.",
    "proj.inprogress"  : "In progress",
    "proj.personal"    : "Personal",
    "tag.team"         : "Team project",
    "tag.stage.bts"    : "BTS SIO internship",

    /* SHARED PROJECT H3 HEADINGS */
    "proj.h3.context"     : "Context",
    "proj.h3.context.pb"  : "Context & problem",
    "proj.h3.overview"    : "Overview",
    "proj.h3.features"    : "Features",
    "proj.h3.tech"        : "Technical architecture",
    "proj.h3.learning"    : "What I learned",
    "proj.h3.results"     : "Result",
    "proj.h3.screenshots" : "Project screenshots",
    "proj.h3.skills"      : "Skills validated",

    /* SHARED SIDEBAR */
    "proj.sidebar.infos"       : "Project info",
    "proj.sidebar.stack"       : "Stack",
    "proj.sidebar.other.stage" : "Other internship projects",
    "proj.sidebar.other.mod"   : "Other mod",
    "proj.sidebar.all"         : "← All projects",
    "proj.back"                : "← Back to projects",

    /* ── STAGE DRASI ── */
    "proj.drasi.h3.pages"     : "Pages built",
    "proj.drasi.h3.technical" : "Notable technical points",
    "proj.drasi.h3.security"  : "Security",
    "proj.drasi.context.p1"   : "Developed during a 6-week internship at DSDEN du Morbihan, this website was built in a pair (two BTS SIO trainees) under the supervision of the IT Manager. The project forms the E5 file of the BTS SIO SLAM.",
    "proj.drasi.context.p2"   : "Objective: create a 100% static showcase site (HTML/CSS/JS vanilla + PHP for the form) presenting the DRASI team, missions, scope of operations and services. Mandatory compliance with the Rennes Academy graphic charter.",
    "proj.drasi.page.1"       : "Home — general presentation of DRASI",
    "proj.drasi.page.2"       : "Our history — history of the department (formerly DSII)",
    "proj.drasi.page.3"       : "Our teams — members and roles",
    "proj.drasi.page.4"       : "Our missions — scope of operations",
    "proj.drasi.page.5"       : "Our perimeter — interactive map (Leaflet.js)",
    "proj.drasi.page.6"       : "Operated services — list of managed services",
    "proj.drasi.page.7"       : "Governance — committee structure",
    "proj.drasi.page.8"       : "Contact us — secure form (reCAPTCHA v2 + PHP)",
    "proj.drasi.tech.1"       : "Component architecture: header, footer and cookie banner loaded via fetch() to avoid duplication",
    "proj.drasi.tech.2"       : "Interactive geographic perimeter map with Leaflet.js",
    "proj.drasi.tech.3"       : "Secure contact form: reCAPTCHA v2, server-side PHP validation, sent via mail()",
    "proj.drasi.tech.4"       : "Custom analytics system (GDPR-compliant): pages visited, time spent, sources — localStorage storage, CSV export",
    "proj.drasi.tech.5"       : "Rennes Academy graphic charter compliance (colours, typography, Marianne logo)",
    "proj.drasi.tech.6"       : "Cross-browser testing: Chrome, Firefox, Edge, Safari — Lighthouse audit",
    "proj.drasi.tech.7"       : "Apache 2.4 Linux production deployment, versioned on GitHub",
    "proj.drasi.tech.8"       : "Accessibility: semantic tags, WCAG contrast ratios, keyboard navigation",
    "proj.drasi.sec.1"        : "HTTPS with SSL certificate, httpOnly + SameSite cookies",
    "proj.drasi.sec.2"        : "Apache headers: X-Frame-Options, X-XSS-Protection, Content-Security-Policy",
    "proj.drasi.sec.3"        : "reCAPTCHA v2 on the contact form",
    "proj.drasi.sec.4"        : "Double validation: client-side (HTML5) + server-side (PHP)",
    "proj.drasi.meta.date"    : "Dec. 2024 – Jan. 2025 (6 wks)",
    "proj.drasi.meta.org"     : "DSDEN du Morbihan — DRASI",
    "proj.drasi.meta.location": "Vannes (56)",
    "proj.drasi.meta.team"    : "2 BTS SIO trainees",
    "proj.drasi.meta.client"  : "Client: IT Manager",
    "proj.drasi.meta.dossier" : "E5 file — BTS SIO SLAM",

    /* ── STAGE GRR ── */
    "proj.grr.h3.done"        : "What I did",
    "proj.grr.h3.troubleshoot": "Troubleshooting resolved",
    "proj.grr.context.p1"     : "DSDEN du Morbihan needed a centralised system so that teams could book IT equipment (rooms, hardware) without relying on informal exchanges. I deployed and configured the open-source software GRR (Resource Reservation Management).",
    "proj.grr.result.p1"      : "GRR is accessible from all workstations on the internal network via http://infra56/reservations. A complete installation guide was provided to facilitate service handover.",
    "proj.grr.done.1"         : "Installation and configuration of WAMP Server on Windows 11 (local server)",
    "proj.grr.done.2"         : "Installation of Visual C++ Redistributable prerequisites",
    "proj.grr.done.3"         : "Deployment of GRR from GitHub (JeromeDevome/GRR) into the /reservations directory",
    "proj.grr.done.4"         : "Creation of the MySQL database grr via phpMyAdmin",
    "proj.grr.done.5"         : "Apache configuration for network access: editing httpd.conf and VirtualHosts",
    "proj.grr.done.6"         : "Opening Windows Firewall on port 80 (TCP)",
    "proj.grr.done.7"         : "Hosts file configuration for internal naming: infra56/reservations",
    "proj.grr.done.8"         : "Writing a complete installation guide for handover and maintenance",
    "proj.grr.fix.1"          : "Port 80 occupied (Skype, IIS) → identifying and freeing the port",
    "proj.grr.fix.2"          : "Apache 403 error → correcting access rights (Require all granted)",
    "proj.grr.fix.3"          : "Network access impossible → VirtualHost configuration + firewall rules",
    "proj.grr.meta.date"      : "2024–2025",
    "proj.grr.meta.org"       : "DSDEN du Morbihan",
    "proj.grr.meta.location"  : "Vannes (56)",
    "proj.grr.meta.dossier"   : "BTS SIO SLAM — AFTEC",
    "proj.grr.meta.deliverable": "Deliverables: operational GRR + documentation",

    /* ── STAGE NOMMAGE ── */
    "proj.nommage.h3.done"    : "What I built",
    "proj.nommage.h3.formula" : "The Python formula (Grist)",
    "proj.nommage.context.p1" : "DSDEN technicians manually named every new computer workstation when integrating it into the network. This was error-prone (typos, duplicates, inconsistencies with the inventory). The department needed an automated tool complying with the French National Education naming conventions.",
    "proj.nommage.context.p2" : "Built in a pair with another trainee, under the supervision of the Deputy IT Manager. High priority — this service did not exist before.",
    "proj.nommage.formula.p1" : "The heart of the project is a Python formula written directly in Grist. It constructs the workstation name by:",
    "proj.nommage.done.1"     : "Learning Grist — a collaborative database tool hosted on Toutatice (National Education)",
    "proj.nommage.done.2"     : "Designing reference tables: OS, hardware models, districts, schools (EPLE), department",
    "proj.nommage.done.3"     : "Building the Grist entry form accessible to technicians",
    "proj.nommage.done.4"     : "Python formula in Grist (generer_code_resu()) to automatically generate a unique name",
    "proj.nommage.done.5"     : "Incrementation logic: the generated name includes the department code, district identifier and an auto-incremented sequential number without duplicates",
    "proj.nommage.done.6"     : "CSV export compatible with MDT Web for Windows deployment",
    "proj.nommage.done.7"     : "Testing on a dedicated workstation, test sessions by user type",
    "proj.nommage.done.8"     : "Technical documentation and user guide",
    "proj.nommage.formula.1"  : "Retrieving the department number (56) and the district name",
    "proj.nommage.formula.2"  : "Extracting the last 3 characters of the district name and the identifier in brackets",
    "proj.nommage.formula.3"  : "Iterating over all existing entries to collect numbers already used in the same group (same department + same district)",
    "proj.nommage.formula.4"  : "Assigning the smallest available number (1–99, formatted as 2 digits)",
    "proj.nommage.formula.5"  : "Returning the final name: 56-XXX-IDEN-01",
    "proj.nommage.meta.date"  : "July 2025 (~10 days)",
    "proj.nommage.meta.org"   : "DSDEN du Morbihan — DSI",
    "proj.nommage.meta.team"  : "2 trainees + Deputy IT Manager",
    "proj.nommage.meta.priority": "High priority",
    "proj.nommage.meta.dossier": "BTS SIO SLAM — AFTEC",

    /* ── STAGE REMP ── */
    "proj.remp.h3.done"       : "What was completed",
    "proj.remp.h3.notdone"    : "What could not be delivered",
    "proj.remp.unfinished.title": "Unfinished project",
    "proj.remp.unfinished.p1" : "This project could not be finalised due to budget and hardware constraints from the client department. The design and architecture were delivered, but the full deployment could not be completed within the internship timeline.",
    "proj.remp.context.p1"    : "Districts managed teacher substitutions through daily email exchanges and Excel files. This system was time-consuming, error-prone and difficult to track for senior management.",
    "proj.remp.context.p2"    : "Built in a pair (two BTS SIO trainees) under the supervision of the Deputy IT Manager. The deadline was the client's departure (July 2025).",
    "proj.remp.learning.p1"   : "Beyond the technical aspects, this project confronted me with the reality of professional projects: budget and organisational constraints can block a technically viable project. Priority management, communication with the client, adapting to the unexpected.",
    "proj.remp.done.1"        : "Requirements analysis with the client (IT Manager)",
    "proj.remp.done.2"        : "Design of the data architecture in Grist",
    "proj.remp.done.3"        : "Creation of reference tables (districts, databases, departments)",
    "proj.remp.done.4"        : "Data entry forms per district",
    "proj.remp.done.5"        : "Summary table structure for senior management",
    "proj.remp.done.6"        : "User rights management prototype",
    "proj.remp.done.7"        : "Partial technical documentation and user guide",
    "proj.remp.notdone.1"     : "Full deployment on the National Education Toutatice infrastructure",
    "proj.remp.notdone.2"     : "Integration with existing tools (lack of hardware resources)",
    "proj.remp.notdone.3"     : "User testing with district staff",
    "proj.remp.notdone.4"     : "Final acceptance by the client",
    "proj.remp.meta.date"     : "July 2025 (~13 days planned)",
    "proj.remp.meta.org"      : "DSDEN du Morbihan — DSI",
    "proj.remp.meta.team"     : "2 BTS SIO trainees",
    "proj.remp.meta.priority" : "High priority — unfinished",
    "proj.remp.meta.stop"     : "Stopped: budget and hardware constraints",
    "proj.remp.meta.dossier"  : "BTS SIO SLAM — AFTEC",
    "proj.remp.sidebar.stack" : "Planned stack",

    /* ── MANGATEC ── */
    "proj.mangatec.h3.context"  : "Context & objectives",
    "proj.mangatec.h3.features" : "Features built",
    "proj.mangatec.h3.roles"    : "Role management (Spatie Laravel Permission)",
    "proj.mangatec.h3.tech"     : "Technical architecture",
    "proj.mangatec.h3.infra"    : "Virtualised infrastructure",
    "proj.mangatec.h3.learning" : "What I learned",
    "proj.mangatec.context.p1"  : "Mangatec is a web application for managing a media library specialised in manga (Japanese comics). This project forms the E6 file of the BTS SIO SLAM, completed at AFTEC in Vannes.",
    "proj.mangatec.context.p2"  : "The objective was to design and deploy a complete application allowing media library members to browse and manage the manga catalogue, with differentiated rights depending on the user's role.",
    "proj.mangatec.roles.p1"    : "Three distinct access levels, managed via the Spatie Laravel Permission package:",
    "proj.mangatec.infra.p1"    : "The project was deployed in a virtualised environment, reproducing a real client/server architecture:",
    "proj.mangatec.feat.1"      : "UC1 — Authentication: secure registration, login and logout (Laravel Breeze / Auth)",
    "proj.mangatec.feat.2"      : "UC2 — Catalogue browsing: manga list, search by title / author / genre, detailed display",
    "proj.mangatec.feat.3"      : "UC3 — Catalogue management (moderator / admin): adding, editing, deleting mangas and series",
    "proj.mangatec.feat.4"      : "UC4 — Administration (admin only): user management, role assignment, supervision",
    "proj.mangatec.role.1"      : "User — read-only: browse catalogue, search",
    "proj.mangatec.role.2"      : "Moderator — editorial management: adding and editing manga entries, catalogue management",
    "proj.mangatec.role.3"      : "Administrator — full control: user management, role assignment, complete administration",
    "proj.mangatec.tech.1"      : "Framework: Laravel 11 — MVC architecture, named routes, middlewares",
    "proj.mangatec.tech.2"      : "Backend: PHP 8.2 — Eloquent ORM, Many-to-Many relations (mangas ↔ genres), migrations, seeders",
    "proj.mangatec.tech.3"      : "Database: MySQL 8.0 — complete relational schema",
    "proj.mangatec.tech.4"      : "Templates: Blade — reusable components, shared layouts",
    "proj.mangatec.tech.5"      : "Permissions: Spatie Laravel Permission — roles and permissions stored in database",
    "proj.mangatec.infra.1"     : "Server VM (Ubuntu Server): Apache2, PHP 8.2, MySQL 8.0, Laravel application",
    "proj.mangatec.infra.2"     : "Client VM (Ubuntu Desktop): application access via browser",
    "proj.mangatec.infra.3"     : "Local network connection between VMs — simulating a production environment",
    "proj.mangatec.learn.1"     : "Getting started with Laravel 11: routing, controllers, models, Eloquent",
    "proj.mangatec.learn.2"     : "Role and permission management with Spatie — clear separation of rights",
    "proj.mangatec.learn.3"     : "Designing relational schemas and migrations",
    "proj.mangatec.learn.4"     : "Deployment on Apache Linux in a virtualised environment",
    "proj.mangatec.learn.5"     : "Writing technical documentation (E6 file BTS SIO)",
    "proj.mangatec.meta.date"   : "2024 – 2025",
    "proj.mangatec.meta.school" : "AFTEC Vannes",
    "proj.mangatec.meta.dossier": "E6 file — BTS SIO SLAM",
    "proj.mangatec.meta.team"   : "Individual project",
    "proj.mangatec.meta.infra"  : "2 Ubuntu VMs (client + server)",

    /* ── PORTFOLIO ── */
    "proj.portfolio.h3.overview" : "Overview",
    "proj.portfolio.h3.features" : "Features",
    "proj.portfolio.h3.tech"     : "Technical choices",
    "proj.portfolio.overview.p1" : "This portfolio is one of the flagship projects of the BTS SIO SLAM. Its purpose is to present my profile, skills and work to future employers or recruiters.",
    "proj.portfolio.overview.p2" : "Built entirely in HTML, CSS and vanilla JavaScript (no framework), it implements modern web development best practices.",
    "proj.portfolio.feat.1"      : "Multi-page architecture with consistent navigation",
    "proj.portfolio.feat.2"      : "Responsive design (mobile, tablet, desktop)",
    "proj.portfolio.feat.3"      : "Bilingual FR/EN translation system (localStorage)",
    "proj.portfolio.feat.4"      : "Scroll animations (Intersection Observer API)",
    "proj.portfolio.feat.5"      : "Skill bar animations",
    "proj.portfolio.feat.6"      : "Project filter by category",
    "proj.portfolio.feat.7"      : "Typing animation in the hero section",
    "proj.portfolio.feat.8"      : "Hamburger menu for mobile",
    "proj.portfolio.feat.9"      : "Cookie management banner",
    "proj.portfolio.feat.10"     : "PDF resume preview and download",
    "proj.portfolio.tech.1"      : "Zero dependencies: pure HTML/CSS/JS, no framework",
    "proj.portfolio.tech.2"      : "CSS custom properties (variables) for visual consistency",
    "proj.portfolio.tech.3"      : "Google Fonts (Inter + JetBrains Mono)",
    "proj.portfolio.tech.4"      : "Dark theme inspired by developer interfaces",
    "proj.portfolio.tech.5"      : "Accessibility: semantic tags, aria-labels, visible focus",
    "proj.portfolio.sidebar.info": "Information",
    "proj.portfolio.meta.date"   : "2024 – 2026 (in progress)",
    "proj.portfolio.meta.school" : "AFTEC Vannes",
    "proj.portfolio.meta.bts"    : "BTS SIO SLAM",
    "proj.portfolio.meta.team"   : "Individual project",
    "proj.portfolio.sidebar.tech": "Technologies",
    "proj.portfolio.cta.view"    : "View portfolio",

    /* ── SPLENDOR ── */
    "proj.splendor.h3.context"   : "Context",
    "proj.splendor.h3.game"      : "The Splendor game",
    "proj.splendor.h3.developed" : "What we developed",
    "proj.splendor.h3.skills"    : "Skills validated",
    "proj.splendor.context.p1"   : "This project was completed at the end of the 2nd year of the Mathematics & Computer Science degree at UBS in Vannes, in a team of three. It was the validation project for Java programming skills, with a final oral defence before a panel to present the technical choices and demonstrate the game.",
    "proj.splendor.context.p2"   : "The objective: implement the board game Splendor in Java from scratch — from the game rules to the playable CLI interface, including full game state management.",
    "proj.splendor.game.p1"      : "Splendor is a strategy game where players collect tokens representing precious gems to buy development cards. These cards allow acquiring more powerful cards and attracting nobles to score prestige points. The first player to reach 15 prestige points wins.",
    "proj.splendor.dev.1"        : "Complete entity modelling: players, cards (3 levels), tokens (5 gems + joker), nobles",
    "proj.splendor.dev.2"        : "Board management: stacks by level, draw pile, card reservation",
    "proj.splendor.dev.3"        : "Complete game logic: token collection (limit rules), card purchase, reservation, noble attraction",
    "proj.splendor.dev.4"        : "Scoring system and end-of-game detection (15 pts, last complete round)",
    "proj.splendor.dev.5"        : "Command-line interface (CLI) readable and playable for 2–4 players",
    "proj.splendor.dev.6"        : "Turn management and validation of illegal actions",
    "proj.splendor.skill.1"      : "Object-oriented programming: inheritance, encapsulation, polymorphism, interfaces",
    "proj.splendor.skill.2"      : "Java multi-class and multi-package architecture design",
    "proj.splendor.skill.3"      : "Algorithms: state machine, game loop, edge case handling",
    "proj.splendor.skill.4"      : "Teamwork, task distribution, versioning with Git",
    "proj.splendor.skill.5"      : "Technical communication: oral defence and justification of design choices",
    "proj.splendor.meta.date"    : "End of 2nd year degree (2023)",
    "proj.splendor.meta.school"  : "UBS Vannes",
    "proj.splendor.meta.degree"  : "Mathematics & Computer Science degree",
    "proj.splendor.meta.team"    : "Group project (trio)",
    "proj.splendor.meta.defence" : "Oral defence before panel",

    /* ── ISLE OF BERK ── */
    "proj.isle.h3.overview"      : "Overview",
    "proj.isle.h3.features"      : "Planned / in-progress features",
    "proj.isle.h3.learning"      : "Technical benefits",
    "proj.isle.h3.status"        : "Current status",
    "proj.isle.overview.p1"      : "Isle of Berk is a personal Minecraft mod project developed in Java with the Minecraft Forge API. It draws directly from the DreamWorks Dragons franchise (How to Train Your Dragon) — tameable dragons, the Isle of Berk, iconic characters.",
    "proj.isle.overview.p2"      : "This project lets me deepen my mastery of object-oriented programming in Java in a concrete and stimulating context, while exploring the Forge APIs to create original game content.",
    "proj.isle.status.p1"        : "The project is in active development. The first dragon entities are being implemented with their basic behaviour system.",
    "proj.isle.feat.1"           : "Adding multiple dragon species (custom entities)",
    "proj.isle.feat.2"           : "Taming system and trust-building mechanic",
    "proj.isle.feat.3"           : "Flying mechanic riding on dragons",
    "proj.isle.feat.4"           : "Special attacks per species (fire, plasma, etc.)",
    "proj.isle.feat.5"           : "New procedurally generated islands",
    "proj.isle.feat.6"           : "New biome inspired by the Nordic archipelago",
    "proj.isle.feat.7"           : "Crafting of equipment and saddles for dragons",
    "proj.isle.feat.8"           : "NPCs (film characters) with dialogue",
    "proj.isle.learn.1"          : "Advanced OOP patterns in Java (inheritance, interfaces, generics)",
    "proj.isle.learn.2"          : "Understanding the Forge API: registries, events, renderers",
    "proj.isle.learn.3"          : "Managing complex entities (AI, pathfinding, states)",
    "proj.isle.learn.4"          : "Working with JSON files (3D models, recipes)",
    "proj.isle.learn.5"          : "Solo project management with Git versioning",
    "proj.isle.meta.date"        : "In progress",
    "proj.isle.meta.type"        : "Personal project",
    "proj.isle.meta.team"        : "Solo",
    "proj.isle.meta.target"      : "Minecraft Java Edition",
    "proj.isle.wip"              : "Under development",

    /* ── MONEY MOD ── */
    "proj.money.h3.overview"     : "Overview",
    "proj.money.h3.features"     : "Features",
    "proj.money.h3.tech"         : "Technical architecture",
    "proj.money.h3.learning"     : "What it brings me",
    "proj.money.overview.p1"     : "Money Mod adds a real economy system to Minecraft that does not exist natively in the game. The original idea: allow server players to trade in a structured way, with physical currency (craftable coins) and NPC merchants.",
    "proj.money.feat.1"          : "Adding coins (bronze, silver, gold) — craftable items",
    "proj.money.feat.2"          : "Per-player wallet system (currency storage)",
    "proj.money.feat.3"          : "NPC merchants with configurable buy/sell catalogue",
    "proj.money.feat.4"          : "Player-to-player transactions via commands or interface",
    "proj.money.feat.5"          : "Transaction history (log)",
    "proj.money.feat.6"          : "Configurable economic balancing (exchange rates, prices)",
    "proj.money.tech.1"          : "Custom items (coins) with crafting logic",
    "proj.money.tech.2"          : "Merchant entities with inventory and basic AI",
    "proj.money.tech.3"          : "Player data persistence system (NBT / JSON)",
    "proj.money.tech.4"          : "Custom commands registered via Forge",
    "proj.money.tech.5"          : "Forge event handling (player interaction, crafting...)",
    "proj.money.learn.1"         : "Practice of persistent data management in Java",
    "proj.money.learn.2"         : "Designing a complex system with many interactions",
    "proj.money.learn.3"         : "Experience with Forge registries and the mod lifecycle",
    "proj.money.learn.4"         : "Systems thinking: balancing and economic consistency",
    "proj.money.meta.type"       : "Personal project",
    "proj.money.meta.team"       : "Solo",
    "proj.money.meta.target"     : "Minecraft Java Edition",
    "proj.money.meta.api"        : "Minecraft Forge API",

    /* PARCOURS */
    "parcours.title"    : "My background",
    "parcours.subtitle" : "Academic education and professional experience",
    "parcours.label"    : "Who I am",
    "parcours.edu"      : "📚 Education",
    "parcours.exp"      : "💼 Experience",
    "parcours.inprogress": "In progress",
    "parcours.bts.desc" : "Training in Software Solutions and Business Applications. Web development (Laravel, PHP, HTML/CSS/JS), databases, networking, agile methods. 10-week cumulative internship at DSDEN du Morbihan.",
    "parcours.licence.desc": "Object-oriented programming with Java, algorithms, Python, SwiProlog, web development (HTML/CSS/PHP/JS), SQL databases. Notable projects: Splendor board game in Java (2nd-year group project, oral defence), Conway's Game of Life, web practicals.",
    "parcours.stage.desc": "10 weeks cumulative. Development of an institutional showcase website, deployment of a GRR room-booking system, automatic computer naming tool (Grist + Python), substitute teacher management service (REMP).",
    "parcours.caisse.desc": "Shelf management, cashiering, customer service. Position held alongside returning to studies.",
    "parcours.rayon.desc": "Customer service, multi-aisle shelf stacking, handling unexpected situations. 2 years of experience alongside studies.",
    "parcours.cta.cv"   : "Download my resume",
    "parcours.cta.contact": "Contact me",

    /* CONTACT */
    "contact.label"       : "Let's connect",
    "contact.title"       : "Contact me",
    "contact.subtitle"    : "A question, an apprenticeship opportunity? Write to me directly.",
    "contact.phone"       : "Phone",
    "contact.location"    : "Location",
    "contact.mobility"    : "Mobility",
    "contact.availability": "Availability",
    "contact.license"     : "Driving license B — own vehicle",
    "contact.available"   : "Looking for apprenticeship — eligible for €5,000 grant",
    "contact.dl.cv"       : "⬇ Download my resume",
    "form.name"           : "Your name",
    "form.company"        : "Company (optional)",
    "form.email.label"    : "Your email address",
    "form.subject"        : "Subject",
    "form.message"        : "Message",
    "form.name.ph"        : "John Smith",
    "form.company.ph"     : "Company name",
    "form.subject.ph"     : "Apprenticeship proposal, question...",
    "form.message.ph"     : "Your message...",
    "form.notice"         : "This form opens your email client (Outlook, Thunderbird, Gmail...) with the information pre-filled.",
    "form.submit"         : "Send message →",
    "form.success"        : "✓ Your email client has been opened with the message pre-filled.",

    /* CV */
    "cv.title"    : "My Resume",
    "cv.subtitle" : "Download my full curriculum vitae",
    "cv.download" : "Download Resume (PDF)",
    "cv.view"     : "View fullscreen",

    /* COOKIE */
    "cookie.title"  : "Cookie settings",
    "cookie.text"   : "This site uses localStorage to save your preferences (language, cookie). No personal data is collected or transmitted.",
    "cookie.accept" : "Accept",
    "cookie.refuse" : "Decline",

    /* FOOTER */
    "footer.copy"   : "Jean-Baptiste Noblet — Portfolio",
    "footer.made"   : "Built with HTML / CSS / JS",
  }
};

(function initTranslate() {
  const btn = document.getElementById('langToggle');
  let lang = localStorage.getItem('lang') || 'fr';

  function apply(l) {
    lang = l;
    localStorage.setItem('lang', l);
    document.documentElement.lang = l;
    if (btn) btn.textContent = l === 'fr' ? '🌐 EN' : '🌐 FR';

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      const val = i18n[l]?.[key];
      if (!val) return;

      /* Special handling for typing phrases */
      if (el.classList.contains('hero-typing-text')) {
        el.dataset.phrases = val;
        return;
      }
      el.textContent = val;
    });

    /* Placeholders */
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      const val = i18n[l]?.[key];
      if (val) el.setAttribute('placeholder', val);
    });

    /* Update href of CTA buttons that might change language */
    document.querySelectorAll('[data-i18n-href]').forEach(el => {
      const key = el.getAttribute('data-i18n-href');
      const val = i18n[l]?.[key];
      if (val) el.setAttribute('href', val);
    });
  }

  apply(lang);

  if (btn) {
    btn.addEventListener('click', () => apply(lang === 'fr' ? 'en' : 'fr'));
  }
})();
